[package]
name = "summer-boot"
version = "0.1.0"
rust-version = "1.60.0"
edition = "2021"
description = "summer boot web2"
authors = [
    "James Zow <Jameszow@163.com>"
]
license = "Apache-2.0"

[features]
default = ["macros"]

macros = [
    "summer-boot-macro"
]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"]}
routefinder = "0.5.0"

#async
async-std = { version = "1.8.0", features = ["attributes"] }
async-trait = "0.1.41"
async-channel = "1.5.1"
async-dup = "1.2.2"

#pin
pin-project = "1.0.2"
pin-project-lite = "0.2.4"

# http middleware
http-types = { version = "2.11.0", default-features = false, features = ["fs"] }
httparse = "1.6"
futures-util = "0.3.6"


# summer dependencies
summer-boot-actuator = { version = "0.1.0", path = "../summer-boot-actuator"}
summer-boot-macro = { version = "0.1.0", path = "../summer-boot-macro", optional = true }

#log
femme = { version = "2.1.1"}
kv-log-macro = "1.0.7"
log = { version = "0.4.13", features = ["kv_unstable_std"] }