[package]
name = "summer-boot"
version = "0.1.0"
rust-version = "1.60.0"
edition = "2021"
description = "summer boot web2"
authors = [
    "James Zow <Jameszow@163.com>"
]
license = "Apache-2.0"

[features]
default = ["macros"]

macros = [
    "summer-boot-codegen"
]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"]}
socket2 = "0.4.4"
tracing = { version = "0.1", default-features = false, features = ["std"] }
httparse = "1.6"
pin-project-lite = "0.2.4"
async-std = { version = "1.8.0", features = ["attributes"] }
async-trait = "0.1.41"
async-h1 = { version = "2.3.0"}
kv-log-macro = "1.0.7"
log = { version = "0.4.13", features = ["kv_unstable_std"] }
http-client = { version = "6.1.0", default-features = false }
http-types = { version = "2.11.0", default-features = false, features = ["fs"] }
routefinder = "0.5.0"
futures-util = "0.3.6"
femme = { version = "2.1.1"}
h2 = "0.3"

# summer dependencies
summer-boot-actuator = { version = "0.1.0", path = "../summer-boot-actuator"}
summer-boot-codegen = { version = "0.1.0", path = "../summer-boot-codegen", optional = true }
